#!/bin/sh

#script to simulate klogd for userspace testing

(

#activate the following lines if you want to get a message when a signal
#is received

#trap "echo klogd: SIGUSR1" SIGUSR1 
#trap "echo klogd: SIGUSR2" SIGUSR2
#trap "echo klogd: SIGTERM -\> exiting ; exit 0" SIGTERM
while true; do sleep 1; done
)&
