#!/bin/sh

echo "Creating rc*.d directories..."
mkdir -p rc.d/rc{0,1,2,3,4,5,6,sysinit}.d

echo "Making symlinks in rc.d/rc0.d..." &&
cd rc.d/rc0.d &&
ln -s ../init.d/sysklogd    K40sysklogd &&
ln -s ../init.d/network     K50network &&
ln -s ../init.d/sendsignals K60sendsignals &&
ln -s ../init.d/mountfs     K70mountfs &&
ln -s ../init.d/swap        K80swap &&
ln -s ../init.d/localnet    K90localnet &&
ln -s ../init.d/halt        K99halt &&

echo "Making symlinks in rc.d/rc1.d..." &&
cd ../rc1.d &&
ln -s ../init.d/sysklogd K80sysklogd &&
ln -s ../init.d/network  K90network &&

echo "Making symlinks in rc.d/rc2.d..." &&
cd ../rc2.d &&
ln -s ../init.d/network  K90network &&
ln -s ../init.d/sysklogd S10sysklogd &&

echo "Making symlinks in rc.d/rc3.d..." &&
cd ../rc3.d &&
ln -s ../init.d/sysklogd S10sysklogd &&
ln -s ../init.d/network  S20network &&

echo "Making symlinks in rc.d/rc4.d..." &&
cd ../rc4.d &&
ln -s ../init.d/sysklogd S10sysklogd &&
ln -s ../init.d/network  S20network &&

echo "Making symlinks in rc.d/rc5.d..." &&
cd ../rc5.d &&
ln -s ../init.d/sysklogd S10sysklogd &&
ln -s ../init.d/network  S20network &&

echo "Making symlinks in rc.d/rc6.d..." &&
cd ../rc6.d &&
ln -s ../init.d/sysklogd    K40sysklogd &&
ln -s ../init.d/network     K50network &&
ln -s ../init.d/sendsignals K60sendsignals &&
ln -s ../init.d/mountfs     K70mountfs &&
ln -s ../init.d/swap        K80swap &&
ln -s ../init.d/localnet    K90localnet &&
ln -s ../init.d/reboot      K99reboot &&

echo "Making symlinks in rc.d/rcsysinit.d..."
cd ../rcsysinit.d &&
ln -s ../init.d/swap S10swap &&
ln -s ../init.d/mountproc S20mountproc &&
ln -s ../init.d/checkfs S30checkfs &&
ln -s ../init.d/mountfs S40mountfs &&
ln -s ../init.d/cleanfs S50cleanfs &&
ln -s ../init.d/setclock S60setclock &&
ln -s ../init.d/loadkeys S70loadkeys &&
ln -s ../init.d/localnet S80localnet &&

echo "Done."
