#!/bin/sh
# Begin $network_devices/ifdown

# Written by Nathan Coulson <nathan@linuxfromscratch.org>
#        and Kevin P Fleming <kpfleming@linuxfromscratch.org>
#
# the IFCONFIG variable is passed to the scripts found in the services directory,
# to indicate what file the service should source to get environmental variables.

. /etc/sysconfig/rc 
. $rc_functions 

if [ "$2" != "" ]
then
	for file in ${@#$1}
	do
	  FILES="$FILES $network_devices/ifconfig.$1/$file"
	done
elif [ -d "$network_devices/ifconfig.$1" ]
then
  FILES="$network_devices/ifconfig.$1/*"
else
  FILES="$network_devices/ifconfig.$1"
fi

for file in $FILES
do
	if [ ! -f "$file" ]
	then
		echo "$file was not a file"
		continue
	fi
	(
		. $file
		# Will not process this service if started by hotplug, and ONHOTPLUG
		#	is not set to yes
		if [ "$IN_HOTPLUG" = "1" -a "$ONHOTPLUG" != "yes" ]
		then
		  continue
		fi

		if [ -n "$SERVICE" -a -x "$network_devices/services/$SERVICE" ]
		then
			IFCONFIG=$file \
				$network_devices/services/${SERVICE} $1 down
		else
			echo -n "Unable to process $file, Either the SERVICE variable was not set, "
			echo "or the script in question cannot be executed"
			continue
		fi
	)
done

# End $network_devices/ifdown
