#!/bin/sh
# Begin $network_devices/ifup

# Written by Nathan Coulson <nathan@linuxfromscratch.org>

. /etc/sysconfig/rc 
. $rc_functions 
. $network_devices/ifconfig.$1 

# Will exit if it is started by the hotplug system, but the configuration file
# does not mention ONHOTPLUG=yes
if [ "$IN_HOTPLUG" = "1" -a "$ONHOTPLUG" != "yes" ]
then
  exit 0
fi

if [ -f $network_devices/ifup-$1 ]
then
	$network_devices/ifup-$1
else
	if [ -z $SERVICE ]
	then
		echo -n "SERVICE variable missing from ifconfig.$1, "
		echo "using static"
		SERVICE=static
	fi
	if [ ! -f $network_devices/services/$SERVICE ]
	then
		echo -n "Unknown Service: $SERVICE, cannot continue"
		exit 1
	fi
	$network_devices/services/${SERVICE} $1 up
fi

# End $network_devices/ifup
