#!/bin/sh
# Begin $rc_base/init.d/checkfs - File System Check Script

# Based on checkfs script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# Patch to handle all fsck variants by A. Luebke - luebke@users.sourceforge.net

# From man fsck
# 0    - No errors
# 1    - File system errors corrected
# 2    - System should be rebooted
# 4    - File system errors left uncorrected
# 8    - Operational error
# 16   - Usage or syntax error
# 32   - Fsck canceled by user request
# 128  - Shared library error

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		if [ -f /fastboot ]
		then
			boot_mesg "Fast boot requested, will not perform file system checks"
			print_status warning
			exit 0
		fi

		boot_mesg "Mounting root file system in read-only mode..."
		mount -n -o remount,ro /
		evaluate_retval

		if [ $? != 0 ]
		then
			print_status failure
			boot_mesg "\nCannot check root filesystem because it could not" $FAILURE
			boot_mesg " be mounted in read-only mode."
			boot_mesg "\n\nWhen you press Enter, this system will be halted."
			boot_mesg "\n\nPress enter to continue..." $NORMAL
			read ENTER
			halt -f
		fi

		if [ -f /forcefsck ]
		then
			boot_mesg "/forcefsck exists, forcing file system check"
			print_status warning
			options="-f"
		else
			options=""
		fi

		boot_mesg "Checking file systems..."
		#Note: -a option used to be -p; but this fails e.g. on fsck.minix
		fsck $options -a -A -C -T
		error_value=$?

		if [ "$error_value" = 1 ]
		then
			boot_mesg "\nFile system errors were found and have been corrected." $WARNING
			boot_mesg "  You may want to double-check that everything was fixed"
			boot_mesg " properly"
			boot_mesg "" $NORMAL
			print_status warning
		fi

		if [ "$error_value" = 0 ]
		then
			print_status success
		fi

		if [ "$error_value" = 2 -o "$error_value" = 3 ]
		then
			print_status failure
			boot_mesg "\nFile system errors were found and have been corrected, but" $WARNING
			boot_mesg " the nature of the errors require this system to be rebooted."
			boot_mesg "\n\nWhen you press enter, this system will be rebooted."
			boot_mesg "\n\nPress Enter to continue..." $NORMAL
			read ENTER
			reboot -f
		fi

		if [ "$error_value" -gt 3 -a "$error_value" -lt 16 ]
		then
			print_status failure
			boot_mesg "File system errors were encountered that couldn't be" $FAILURE
			boot_mesg " fixed automatically.  This system cannot continue to boot"
			boot_mesg " and will therefore be halted until those errors are fixed manually"
			boot_mesg " by a System Administrator"
			boot_mesg "\n\nWhen you press Enter, this system will be halted."
			boot_mesg "\n\nPress Enter to continue..." $NORMAL
			read ENTER
			halt -f
		fi

		if [ "$error_value" -ge 16 ]
		then 
			boot_mesg "\nUnexpected Failure running fsck. Exited with $error_value" $FAILURE
			boot_mesg "" $NORMAL
			print_status failure
			exit $error_value
		fi
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/checkfs
