#!/bin/sh
# Begin $rc_base/init.d/cleanfs - Clean file system

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

# Function to create files/directory on boot.
create_files() {
	# Read in the configuration file.
	exec 9>&0 < /etc/sysconfig/createfiles
	        while read name type perm usr grp dtype maj min junk ; do

			# Ignore comments and blank lines.
        	        case "$name" in
                	        ""|\#*) continue ;;
	                esac

			# Ignore existing files.
        	        if [ ! -e "$name" ]; then
				# Create stuff based on its type.
                	        case "$type" in
                        	        dir)    mkdir "$name"   ;;
                                	file)   :> "$name"      ;;
	                                dev)    case "$dtype" in
        	                                char)   mknod "$name" c $maj $min	;;
                	                        block)  mknod "$name" b $maj $min	;;
                        	                pipe)   mknod "$name" p			;;
	                               	        esac            ;;
        	                        *)      echo "Unknown type: $type" >&2
                	                        continue        ;;
                        	esac

				# Set up the permissions, too.
	                        chown $usr:$grp "$name"
	                        chmod $perm "$name"
	                fi
	        done
	exec 0>&9 9>&-
}

case "$1" in
	start)
		echo "Removing /var/run/* and /var/lock/*"
		rm -rf /var/run/* /var/lock/*
		evaluate_retval

		echo "Creating new /var/run/utmp..."
		> /var/run/utmp && chmod 644 /var/run/utmp
		evaluate_retval

		echo "Removing possible /etc/nologin /fastboot and /forcefsck..."
		rm -f /etc/nologin /fastboot /forcefsck
		evaluate_retval

		echo "Removing /tmp/*"
		find /tmp -xdev -mindepth 1 -depth ! -path '/tmp/lost+found*' \
		  -exec rm -rf {} \;
		evaluate_retval

		if [ -r /etc/sysconfig/createfiles ]; then
			echo "Creating files and directories..."
			create_files
			evaluate_retval
		fi
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/cleanfs
