#!/bin/bash
# Begin $rc_base/init.d/localnet - Loopback device

# Based on localnet sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		echo "Bringing up the loopback interface..."
		ip link set lo up
		ip addr add 127.0.0.1/8 dev label lo dev lo
		evaluate_retval

		echo "Setting hostname to $HOSTNAME..."
		hostname $HOSTNAME
		evaluate_retval
		;;

	stop)
		echo "Bringing down the loopback interface..."
		ip link set lo down
		evaluate_retval
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		echo "Hostname is: $(hostname)"
		ifconfig lo
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/localnet
