#!/bin/sh
# Begin $rc_base/init.d/mountkernfs

# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		if [ ! -e /proc/mounts ]; then
			echo "Mounting proc file system..."
			mount -n /proc
			evaluate_retval
		fi

		# This should be mounted on a 2.6 kernel.
		if grep -q '[[:space:]]sysfs' /proc/filesystems; then
			if [ -d /sys -a ! -d /sys/block ]; then
				echo "Mounting sysfs file system..."
				mount -n /sys
				evaluate_retval
			fi
		fi

		if grep -q '[[:space:]]usbfs' /proc/filesystems; then
			echo "Mounting USB filesystem"
			mount -n /proc/bus/usb
			evaluate_retval
		fi
		;;
	*)
		echo "Usage $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
