#!/bin/sh
# Begin $rc_base/init.d/mountkernfs

# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		if [ ! -e /proc/mounts ]; then
			echo "Mounting proc file system..."
			mount -n /proc
			evaluate_retval
		fi
		;;
	*)
		echo "Usage $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
