#!/bin/sh
# Begin $rc_base/init.d/network - Network Control Script

# Based on ethnet script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# Rewritten by Nathan Coulson <nathan@linuxfromscratch.org>
# Enhanced by Kevin P. Fleming <kpfleming@linuxfromscratch.org>

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		# Start all network interfaces
		for file in $network_devices/ifconfig.*; do
			interface=${file##*/ifconfig.}

			# skip if $file is * (because nothing was found)
			if [ "$interface" = "*" ]; then
				continue
			fi

			# skip if $file ends with ~ (backup files)
			if [ "$file" != "${file%""~""}" ]; then
				continue
			fi

			IN_BOOT=1 $network_devices/ifup $interface
		done
	;;

	stop)
		# Stop all network interfaces
		for file in $network_devices/ifconfig.*; do
			interface=${file##*/ifconfig.}

			# skip if $file is * (because nothing was found)
			if [ "$interface" = "*" ]; then
				continue
			fi

			# skip if $file ends with ~ (backup files)
			if [ "$file" != "${file%""~""}" ]; then
				continue
			fi

			IN_BOOT=1 $network_devices/ifdown $interface
		done
	;;

	restart)
		$0 stop
		sleep 1
		$0 start
	;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
	;;
esac

# End /etc/rc.d/init.d/network
