#!/bin/sh
# Begin $rc_base/init.d/network - Network Control Script

# Based on ethnet script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		# Start all network interfaces which have ONBOOT in them.
		for file in $network_devices/ifconfig.*
		do
			interface=${file##*/ifconfig.}
			# verify that $file is a file, and does not end with a ~
			if [ -r "$file" -a "$file" = "${file%""~""}" ]
			then
				(
					. "$file"
					if [ "$ONBOOT" = "yes" ]; then
						$network_devices/ifup $interface
					fi
				)
			fi
		done

		# Setup the Gateway
		if [ "$GATEWAY" != "" ]
		then
			echo -n "Warning, setting gateway in "
			echo "/etc/sysconfig/network is depreciated"
			echo "Setting up default gateway..."
			route add default gateway $GATEWAY metric 1 \
				dev $GATEWAY_IF
			evaluate_retval
		fi
		;;

	stop)
		if [ "$GATEWAY" != "" ]
		then
			echo -n "Warning, setting gateway in "
			echo "/etc/sysconfig/network is depreciated"
			echo "Removing default gateway..."
			route del -net default
			evaluate_retval
		fi
		# Stop all network interfaces
		for file in $network_devices/ifconfig.*
		do
			interface=${file##*/ifconfig.}
			# verify that $file is a file, and does not end with a ~
			if [ -r "$file" -a "$file" = "${file%""~""}" ]
			then
				(
					. "$file"
					if [ "$ONBOOT" = "yes" ]; then
						$network_devices/ifdown $interface
					fi
				)
			fi
		done


		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

# End /etc/rc.d/init.d/network
