#!/bin/sh
########################################################################
# Begin $rc_base/init.d/syslog-ng
#
# Description : Syslog-ng loader
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting system log daemon..."
		loadproc syslog-ng
		;;

	stop)
		boot_mesg "Stopping system log daemon..."
		killproc syslog-ng
		;;

	reload)
		boot_mesg "Reloading system log daemon config file..."
		reloadproc syslog-ng 1
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc syslog-ng
		;;

	*)
		echo "Usage: ${0} {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/syslog-ng
