.\" Process this file with
.\" groff -man -Tascii lfscmd.1
.\"
.TH LFSCMD 1
.SH NAME
LFSCMD \- Extract LFS/BLFS book commands.
.SH SYNOPSIS
.B lfscmd [options] [index.xml]
.SH DESCRIPTION
.B lfscmd
extracts commands from the LFS and BLFS books. The commands may be
printed, executed, or written to files. lfscmd can record
the title of the current page and select pages which match a regular
expression.

lfscmd tries to conform older books to the new command structure.
For instance, lfscmd removes double ampersands and disregards the
space between command blocks.

lfscmd might be used to:
.TP
*
Reference the build instructions of one or more packages.
.TP
*
Determine the command changes between arbitrary versions
of a particular package, with assistance from diff(1).
.TP
*
Automate installation scripts by executing commands for
one or more packages on the fly.
.SH OPTIONS
.TP
.B -e
Execute commands.
.TP
.B -f
Write commands to their own file.
.TP
.B -a
Strip '&&' in commands.
.TP
.B
-q query
Output pages matching regex query.
.TP
.B -t
Print titles (as comments).
.TP
.B
-x
Give executable permission to the resulting files.
.SH "ENVIRONMENT VARIABLES"
.TP
.SM LFSCMD_BOOK
The full path to the index page of the default book.
.SH AUTHOR
Timothy Bauscher <timothy@linuxfromscratch.org>
