.\" Process this file with
.\" groff -man -Tascii lfscmd.1
.\"
.TH LFSCMD 1
.SH NAME
LFSCMD \- Extract LFS/BLFS book commands.
.SH SYNOPSIS
.B lfscmd [options] INDEX.XML
.SH DESCRIPTION
.B lfscmd
prints the screen commands from the LFS/BLFS book to either
stdout or files.
.SH OPTIONS
.TP
.B -e
Execute commands.
.TP
.B -f
Write commands to their own file.
.TP
.B
-q query
Output pages matching regex query.
.TP
.B -t
Print titles (as comments).
.TP
.B
-x
Give executable permission to the resulting files.
.SH AUTHOR
Timothy Bauscher <timothy@linuxfromscratch.org>
