#!/bin/sh

source /etc/sysconfig/rc 
source $rc_functions 
source $network_devices/ifconfig.$1 

if [ -f $network_devices/ifdown-$1 ]
then
	$network_devices/ifdown-$1
else
	echo "Bringing down the $1 interface..."
	ifconfig $1 down
	evaluate_retval
fi

