#!/bin/sh

source /etc/sysconfig/rc 
source $rc_functions 
source $network_devices/ifconfig.$1 

if [ -f $network_devices/ifup-$1 ]
then
	$network_devices/ifup-$1
else
	if [ -z $IP ]
	then
		echo "IP variable missing for ifconfig.$1, cannot continue"
		exit 1
	fi

	if [ -z $NETMASK ]
	then
		echo -n "NETMASK variable missing for ifconfig.$1, "
		echo "using 255.255.255.0"
		NETMASK=255.255.255.0
	fi

	if [ -z $BROADCAST ]
	then
		echo -n "BROADCAST variable missing for ifconfig.$1, "
		echo "using default address"
	fi

	echo "Bringing up the $1 interface..."
	ifconfig $1 $IP netmask $NETMASK broadcast $BROADCAST
	evaluate_retval
fi

