#!/bin/sh
UTC=no  #set to yes if your hardware clock is set to GMT instead of local time
HOSTNAME=lfs

#List of network devices to be ifconfig'd at boot 
#(excluding the loopback device)
#No spaces are allowed around "[", "]" and "=" !

NET_DEVICE[0]=eth0
NET_ONBOOT[0]=yes    #set to no to not set up this device at boot
NET_IP[0]=192.168.1.1
NET_MASK[0]=255.255.255.0
NET_BROADCAST[0]=192.168.1.255

#NET_DEVICE[1]=eth1
#NET_ONBOOT[1]=yes
#NET_IP[1]=192.168.1.2
#NET_MASK[1]=255.255.255.0
#NET_BROADCAST[1]=192.168.1.255
