#!/bin/sh
# Begin $network_devices/services/static

# Based upon lfs-bootscripts-1.12 $network_devices/if{down,up}
# Rewritten by Nathan Coulson <nathan@linuxfromscratch.org>

. /etc/sysconfig/rc 
. $rc_functions 
. $network_devices/ifconfig.$1

case "$2" in
	up)
		if [ -z $IP ]
		then
			echo "IP variable missing for ifconfig.$1, cannot continue"
			exit 1
		fi

		if [ -z $NETMASK ]
		then
			echo -n "NETMASK variable missing for ifconfig.$1, "
			echo "using /24"
			NETMASK=24
		fi

		if [ -z $BROADCAST ]
		then
			echo -n "BROADCAST variable missing for ifconfig.$1, "
			echo "using default address"
		fi

		echo "Bringing up the $1 interface..."
		ip link set $1 up
		ip addr add $IP/$NETMASK broadcast $BROADCAST label $1 dev $1
		evaluate_retval

		if [ -n "$GATEWAY" ]; then
			if ip route | grep -q default; then; then
				echo "Gateway already setup; skipping..."
				print_status warning
			else
				echo "Setting up default gateway..."
				ip route add default via $GATEWAY dev $1
				evaluate_retval
			fi
		fi
	;;

	down)
		if [ -n "$GATEWAY" ]; then
			echo "Removing default gateway..."
			ip route del default
			evaluate_retval
		fi

		echo "Bringing down the $1 interface..."
		ip link set $1 down
		evaluate_retval
	;;

	*)
		echo "Usage: $0 [interface] {up|down}"
		exit 1
	;;
esac

# End $network_devices/services/static
