#!/bin/sh
# Begin $rc_base/init.d/consolelog

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/consolelog

case "${1}" in

	start)
		sleep "${WAITTIME}"
		boot_mesg "Setting default kernel log level..."
		dmesg -n "${LOGLEVEL}"
		evaluate_retval
	;;
	*)
		echo "Usage: ${0} {start}"
		exit 1
	;;
esac

# End $rc_base/init.d/consolelog

