#!/bin/sh
# Begin $rc_base/init.d/hotplug - Load modules for system devices

# Written by Zack Winkles - winkie@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

# If hotplug is actually present, then set it to be the default manager of
# hotplug events, otherwise quietly exit.
if [ -x /sbin/hotplug ]; then
	echo /sbin/hotplug > /proc/sys/kernel/hotplug
else
	exit 0
fi

case "$1" in
	start|restart|status)
		echo "Loading modules for system devices..."
		for rc in /etc/hotplug/*.rc; do
			$rc $1
		done
		print_status success
		;;
	stop)
		echo "Unloading modules for system devices..."
		for rc in /etc/hotplug/*.rc; do
			$rc $1
		done
		print_status success
		;;
	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/hotplug
