#!/bin/sh
############################################################################
# Begin $rc_base/init.d/startup
#
# Description : Removes etc symlink and untars etc and root
#
# Authors     : Original by Chris Lingard, chris@stockwith.co.uk
#               Modified by Jeremy Huntwork, jhuntwork@linuxfromscratch.org
#
# Date        : 2005-01-26
#
############################################################################

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Unpacking files to /etc..."
		cd /
		/bin/rm  /etc
		/bin/tar xjf /.cdrom/etc.tar.bz2
		evaluate_retval
		echo "Unpacking files to /root..."
		/bin/tar xjf /.cdrom/root.tar.bz2
		evaluate_retval
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/
