#!/bin/sh
# 
# start foo service
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

case "$1" in
  start)
     need $mounted_filesystems || exit_if_any_error
  
     echo 'Starting foo service...'
     loadproc foo --parameter || exit_if_any_error

     echo 'Starting foo additional...'
     fooadditional 
     up_evaluate_retval || exit_if_any_error
     ;;
  stop)
     echo 'Stopping foo service...'
     killproc foo
     
     echo 'Stopping foo additional...'
     killproc fooadditional
     ;;
  reload)
     echo 'Reinitializing foo...'
     reloadproc foo
     reloadproc fooadditional
     ;;
  status)
     statusproc foo
     statusproc fooadditional
     ;;   
  *)
     exit 1
     ;;
esac
    
exit 0

