#!/bin/sh
# 
# start fcron daemon
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

case "$1" in
  start)
     need $mounted_filesystems || exit_if_any_error
  
     echo 'Starting fcron daemon...'
     loadproc fcron -b || exit_if_any_error
     ;;
  stop)
     echo 'Stopping fcron daemon...'
     killproc fcron
     ;;
  reload)
     echo 'Reinitializing fcron...'
     reloadproc fcron
     ;;
  status)
     statusproc fcron
     ;;   
  *)
     exit 1
     ;;
esac
    
exit 0

