#! /bin/sh
#
# speed up /dev/hda
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

case "$1" in
  start)
     echo Speeding up /dev/hda...
     #The following is commented out because running hdparm with the
     #wrong parameters can cause data loss. Do not activate the following
     #line blindly. Read the manpage and change the settings to match your
     #hardware
     #hdparm -q -c1 -q -u1 -q -d1 -q -m16 -q -X66 /dev/hda
     #up_evaluate_retval || exit_if_any_error
     $CURS_UP ; print_status skipped
     ;;
  stop)
     ;;
  *)
     exit 1
     ;;
esac
    
exit 0
