#!/bin/sh
# Begin $rc_base/init.d/console - Sets keymap and screen font

# Based on loadkeys script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# Screen font added by Alexander E. Patrakov

. /etc/sysconfig/rc
. $rc_functions

# Native English speakers probably don't have /etc/sysconfig/console at all
if [ -f /etc/sysconfig/console ]; then
	. /etc/sysconfig/console
else
	exit 0
fi

case "$1" in
	start)
		if [ -n "$KEYMAP" ]; then
			echo -n "Loading keymap..."
			loadkeys $KEYMAP
			evaluate_retval
		fi

		if [ -n "$KEYMAP_CORRECTIONS" ]; then
			echo -n "Correcting keymap..."
			loadkeys $KEYMAP_CORRECTIONS
			evaluate_retval
		fi

		if [ -n "$FONT" ]; then
			echo -n "Setting screen font..."
			setfont $FONT
			evaluate_retval
		fi
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/console
