#!/bin/sh
# Begin $rc_base/init.d/console - Sets keymap and screen font

# Based on loadkeys script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# Screen font added by Alexander E. Patrakov

. /etc/sysconfig/rc
. $rc_functions

# Native English speakers probably don't have /etc/sysconfig/console at all


case "$1" in
	start)
		if [ ! -f /etc/sysconfig/console ]
		then
			exit 0
		fi
		. /etc/sysconfig/console

		if [ ! -z "$KEYMAP" ]
		then
			echo -n "Loading keymap..."
			loadkeys $KEYMAP
			evaluate_retval
		fi
		if [ ! -z "$KEYMAP_ CORRECTIONS" ]
		then
			echo -n "Correcting keymap..."
			loadkeys $KEYMAP_CORRECTION
			evaluate_retval
		fi
		if [ ! -z "$FONT" ]
		then
			echo -n "Setting screen font..."
			setfont $FONT
			evaluate_retval
		fi

		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/console
