#!/bin/sh
########################################################################
# Begin $rc_base/init.d/mountkernfs
#
# Description : Mount proc and sysfs
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg -n "Mounting kernel-based file systems:" ${INFO}

		if ! mountpoint /proc
		then
			boot_mesg -n " /proc" ${NORMAL}
			mount -n /proc || failed=1
		fi

		if mountpoint /sys
		then
			boot_mesg -n "/sys" ${NORMAL}
			mount -n /sys || failed=1
		fi

		boot_mesg "" ${NORMAL}

		(exit ${failed})
		evaluate_retval

		if [ -f "/etc/sysctl.conf" ]
		then
			boot_mesg "Setting kernel runtime parameters..."
			sysctl -p
			evaluate_retval
		fi
		;;
	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
