#!/bin/sh
# Begin $rc_base/init.d/mountkernfs

# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Mounting kernel-based file systems:" ${INFO}

		if [ ! -e /proc/mounts ]
		then
			boot_mesg " /proc" ${NORMAL}
			mount -n /proc || failed=1
		fi

		# This should be mounted on a 2.6 kernel.
		if grep -q '[[:space:]]sysfs' /proc/filesystems
		then
			if [ -d /sys -a ! -d /sys/block ]
			then
				boot_mesg " /sys" ${NORMAL}
				mount -n /sys || failed=1
			fi
		fi

		(exit ${failed})
		evaluate_retval

		if [ -f "/etc/sysctl.conf" ]
		then
			boot_mesg "Setting kernel runtime parameters..."
			sysctl -p
			evaluate_retval
		fi
		;;
	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
