#!/bin/sh
# Begin $rc_base/init.d/network - Network Control Script

# Based on ethnet script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		# Start all network interfaces which have ONBOOT in them.
		for file in $network_devices/ifconfig.* $network_devices/ifconfig.*/*
		do
			interface=${file##*/ifconfig.}
			interface=${interface%%/*}

			# verify that $file is a readable file, and does not end with a ~
			if [ -f "$file" -a "$file" = "${file%""~""}" ]
			then
				(
					. "$file"
					if [ "$file" != "$network_devices/ifconfig.$interface" ]
					then
						ARGS=${file##*/ifconfig.${interface}/}
					fi
					if [ "$ONBOOT" = "yes" ]; then
						$network_devices/ifup $interface $ARGS
					fi
				)
			fi
		done
	;;

	stop)
		# Stop all network interfaces
		for file in $network_devices/ifconfig.* $network_devices/ifconfig.*/*
		do
			interface=${file##*/ifconfig.}
			interface=${interface%%/*}

			# verify that $file is a readable file, and does not end with a ~
			if [ -f "$file" -a "$file" = "${file%""~""}" ]
			then
				(
					. "$file"
					if [ "$file" != "$network_devices/ifconfig.$interface" ]
					then
						ARGS=${file##*/ifconfig.${interface}/}
					fi
					if [ "$ONBOOT" = "yes" ]; then
						$network_devices/ifdown $interface $ARGS
					fi
				)
			fi
		done
	;;

	restart)
		$0 stop
		sleep 1
		$0 start
	;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
	;;
esac

# End /etc/rc.d/init.d/network
