#!/bin/sh
# Begin $rc_base/init.d/reboot - Reboot Script

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	stop)
		reboot -d -f -i
		;;

	*)
		echo "Usage: $0 {stop}"
		exit 1
		;;

esac

# End $rc_base/init.d/reboot
