#!/bin/sh
# Begin $rc_base/init.d/

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting..."
		loadproc
		;;

	stop)
		echo "Stopping..."
		killproc
		;;

	reload)
		echo "Reloading..."
		reloadproc
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/
