#!/bin/sh
# Begin $rc_base/init.d/adsl

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# adsl script written by DJ Lucas  - dj@lucasit.com

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Bringing up the ADSL interface..."
		/usr/sbin/adsl-start
		evaluate_retval
		;;

	stop)
		echo "Bringing down the ADSL interface..."
		/usr/sbin/adsl-stop
		evaluate_retval
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		/usr/sbin/adsl-status
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/adsl
