#!/bin/sh
# Begin $rc_base/init.d/gpm

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org
# GPM specific parts by Mark Hymers - markh@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

if [ -f /etc/sysconfig/mouse ]
	then
	. /etc/sysconfig/mouse
fi

if [ -z "$MDEVICE" ] || [ -z "$PROTOCOL" ]
	then
	echo "Please create an /etc/sysconfig/mouse file containing"
	echo "MDEVICE and PROTOCOL values"
	exit 1;
fi

case "$1" in
	start)
		echo "Starting gpm..."
		loadproc gpm -m $MDEVICE -t $PROTOCOL
		;;

	stop)
		echo "Stopping gpm..."
		killproc gpm
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc gpm
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/gpm
