#!/bin/sh
# Begin $rc_base/init.d/postgresql

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting PostgreSQL daemon..."
		su - postgres -c '/usr/bin/pg_ctl start -W -D /var/pgsql/data \
				-l /var/pgsql/data/logfile -o "-i" '
		evaluate_retval
		;;

	stop)
		echo "Stopping PostgreSQL daemon..."
		/usr/bin/pg_ctl stop -m smart -D /var/pgsql/data
		evaluate_retval
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		/usr/bin/pg_ctl status -D /var/pgsql/data
		;;

	*)
		echo "Usage: $0 {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/postgresql
