#!/bin/sh
# 
# load the default keymap (usually /usr/share/kbd/keymaps/defkeymap*)
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

case "$1" in
  start)
     #need access to /usr/share/...
     need $mounted_filesystems || exit_if_any_error
   
     loadkeys -d
     up_evaluate_retval || exit_if_any_error
     ;;
  stop)
     ;;
  *)
     exit 1
     ;;
esac
    
exit 0

