#! /bin/sh
#
# network loopback interface
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

#sysconfig contains the host name
source $sysconfig_network

case "$1" in
  start)
     echo 'Setting up hostname...'
     hostname $HOSTNAME
     up_evaluate_retval || exit_if_any_error
     
     echo 'Bringing up the loopback interface...'
     ifconfig lo 127.0.0.1
     up_evaluate_retval || exit_if_any_error
     ;;
  stop)
     echo 'Bringing down the loopback interface...'
     ifconfig lo down
     up_evaluate_retval
     ;;
  *)
     exit 1
     ;;
esac
    
exit 0


