#!/bin/sh

#script to simulate syslogd for userspace testing

(

#activate the following lines if you want to get a message
#when a signal is received

#trap "echo syslogd: SIGHUP" SIGHUP
#trap "echo syslogd: SIGTERM -\> exiting; exit 0" SIGTERM
while true; do sleep 1; done 
) &
