#!/bin/sh
#
# compute module dependencies
#

#locate and source functions script
source `PATH=$INIT_D/:/sbin/init.d:/etc/init.d:/etc/rc.d type -p functions`

case "$1" in
  start)
     #need to write dependency file
     need $mounted_filesystems || exit_if_any_error
  
     echo 'Computing kernel module dependencies...'
     depmod -a
     up_evaluate_retval || exit_if_any_error
     ;;
  stop)
     ;;
  *)
     exit 1
     ;;
esac
    
exit 0
