#!/bin/bash
# Begin $rc_base/init.d/cleanfs - Clean file system

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions

echo "Removing /var/run/* and /var/lock/*"
rm -rf /var/run/* /var/lock/*
evaluate_retval

echo "Creating new /var/run/utmp..."
touch /var/run/utmp && chmod 644 /var/run/utmp
evaluate_retval

echo "Removing possible /etc/nologin /fastboot and /forcefsck..."
rm -f /etc/nologin /fastboot /forcefsck
evaluate_retval

# End $rc_base/init.d/cleanfs

