#!/bin/sh
# Begin $rc_base/init.d/halt - Halt Script

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	stop)
		halt -d -f -i -p
		;;
	*)
		echo "Usage: {stop}"
		exit 1
		;;
esac

# End $rc_base/init.d/halt
