#!/bin/bash
# Begin $rc_base/init.d/setclock - Setting Linux Clock

# Based on setclock script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions
source /etc/sysconfig/clock

CLOCKPARAMS="--hctosys"

case "$UTC" in
	yes|true|1)
		CLOCKPARAMS="$CLOCKPARAMS --utc"
		;;
	no|false|0)
		CLOCKPARAMS="$CLOCKPARAMS --localtime"
		;;
esac

echo "Setting clock..."
hwclock $CLOCKPARAMS
evaluate_retval

# End $rc_base/init.d/setclock

