#!/bin/sh
########################################################################
# Begin $rc_base/init.d/consolelog
#
# Description : Change Console Logging
#
# Authors     : Gerard Beekmans - gerard@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       :
#
########################################################################

. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/consolelog

case "${1}" in

	start)
		sleep "${WAITTIME}"
		boot_mesg "Setting default kernel log level..."
		dmesg -n "${LOGLEVEL}"
		evaluate_retval
	;;
	*)
		echo "Usage: ${0} {start}"
		exit 1
	;;
esac

# End $rc_base/init.d/consolelog

