#!/bin/sh
# Begin /etc/init.d/reboot

### BEGIN INIT INFO
# Provides:            halt
# Required-Start:
# Should-Start:
# Required-Stop:       localnet
# Should-Stop:
# Default-Start:
# Default-Stop:        6
# Short-Description:   Reboots the system.
# Description:         Reboots the System.
# X-LFS-Default-Start:
# X-LFS-Default-Stop:  S99
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    stop)
        log_success_msg "Restarting system..."
        reboot -d -f -i
        ;;

    *)
        echo "Usage: ${0} {stop}"
        exit 1
        ;;

esac

# End /etc/init.d/reboot
