#!/bin/sh
# Begin $rc_base/init.d/exim

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting exim..."
		loadproc /usr/sbin/exim -bd -q1m
		;;

	stop)
		echo "Stopping exim..."
		killproc exim
		;;

	status)
		statusproc exim
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|status|restart}"
		exit 1
		;;
esac

# End $rc_base/init.d/exim
