#!/bin/sh
# Begin $rc_base/init.d/portmap

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting RPC Portmap"
		loadproc /sbin/portmap
		;;

	stop)
		echo "Stopping Portmap"
		killproc /sbin/portmap
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;

esac

# End $rc_base/init.d/portmap
