#!/bin/sh
# Begin $rc_base/init.d/proftpd

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting FTP Server..."
		loadproc /usr/sbin/proftpd
		;;

	stop)
		echo "Stopping FTP Server..."
		killproc /usr/sbin/proftpd
		;;

	reload)
		echo "Reloading FTP Server..."
		reloadproc /usr/sbin/proftpd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/proftpd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/proftpd
