#!/bin/sh
# Begin $rc_base/init.d/samba

# Based on sysklogd script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions

case "$1" in
	start)
		echo "Starting nmbd..."
		loadproc /usr/sbin/nmbd -D

		echo "Starting smbd..."
		loadproc /usr/sbin/smbd -D
		;;

	stop)
		echo "Stopping smbd..."
		killproc /usr/sbin/smbd

		echo "Stopping nmbd..."
		killproc /usr/sbin/nmbd
                ;;

	reload)
		echo "Reloading smbd..."
		reloadproc /usr/sbin/smbd

		echo "Reloading nmbd..."
		reloadproc /usr/sbin/nmbd
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	status)
		statusproc /usr/sbin/nmbd
		statusproc /usr/sbin/smbd
		;;

	*)
		echo "Usage: $0 {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/samba
