#!/bin/sh
############################################################################
# Begin $rc_base/init.d/hostname
#
# Description : Sets hostname for livecd
#
# Authors     : Jeremy Huntwork, jhuntwork@linuxfromscratch.org
#
# Date        : 2005-01-28
#
############################################################################

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		echo "Setting hostname to $HOSTNAME..."
		hostname $HOSTNAME
		evaluate_retval
		;;

	*)
		echo "Usage: $0 {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/
