#!/bin/bash
# Begin $rc_base/init.d/halt - Halt Script

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions

halt -d -f -i -p

# End $rc_base/init.d/halt

