#!/bin/bash
# Begin $rc_base/init.d/mountproc

# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions

if [ ! -e /proc/mounts ]; then
	echo "Mounting proc file system..."
	mount -n /proc
	evaluate_retval
fi

# End $rc_base/init.d/mountproc

