#!/bin/bash
# Begin $rc_base/init.d/mountproc

# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions

echo "Mounting proc file system..."
mount /proc
evaluate_retval

# End $rc_base/init.d/mountproc

