#!/bin/sh
# Begin $rc_base/init.d/network - Network Control Script

# Based on ethnet script from LFS-3.1 and earlier.
# Rewritten by Gerard Beekmans  - gerard@linuxfromscratch.org

. /etc/sysconfig/rc
. $rc_functions
. /etc/sysconfig/network

case "$1" in
	start)
		# Start all network interfaces which have ONBOOT in them.
		for file in $(grep -sil "ONBOOT=yes" $network_devices/ifconfig.*)
		do
			interface=${file##*/ifconfig.}
			case "$interface" in
				*~) ;;
				*)
					$network_devices/ifup $interface
					;;
			esac
		done

		# Setup the Gateway
		if [ "$GATEWAY" != "" ]
		then
			echo "Setting up default gateway..."
			route add default gateway $GATEWAY metric 1 \
				dev $GATEWAY_IF
			evaluate_retval
		fi
		;;

	stop)
		if [ "$GATEWAY" != "" ]
		then
			echo "Removing default gateway..."
			route del -net default
			evaluate_retval
		fi

		# Stop all network interfaces
		for file in $(grep -il "ONBOOT=yes" $network_devices/ifconfig.*)
		do
			interface=${file##*/ifconfig.}
			case "$interface" in
				*~) ;;
				*)
					$network_devices/ifdown $interface
					;;
			esac
		done
		;;

	restart)
		$0 stop
		sleep 1
		$0 start
		;;

	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
		;;
esac

# End /etc/rc.d/init.d/network
