#!/bin/bash
# Begin $rc_base/init.d/reboot - Reboot Script

# Written by Gerard Beekmans  - gerard@linuxfromscratch.org

source /etc/sysconfig/rc
source $rc_functions

reboot -d -f -i

# End $rc_base/init.d/reboot

